export { default as App } from './App'
export { default as Navbar } from './Navbar'
export { default as Login } from './Login'
export { default as Posts} from './Posts.js'
export { default as Welcome} from './Welcome.js'
export { default as Register} from './Register'
export { default as Profile } from './Profile'